### ISSUE TITLE
建议在通信中加入加密

### ISSUE THREAD

**Issue by 0x00A0** [WheatBox/WheatCloudSleep#1]
比如对机器生成机器识别码等方法规避可能的DDoS或恶意消息

**Comment by 0x00A0** [comment]
对消息的处理部分也可以转移到客户端,以减轻服务器的工作,这样一来服务器只充当一个身份认证和消息中转的功能

**Comment by WheatBox** [comment]
谢谢，但是这样子风险更大了（因为代码都是开源的），在服务器上我还能稍微管理一下，但是全交给客户端将会极其不可控，不过还是谢谢你的建议了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WheatBox/WheatCloudSleep"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 上午8:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [WheatBox/WheatCloudSleep] 建议在通信中加入加密 (Issue #1)





 
对消息的处理部分也可以转移到客户端,以减轻服务器的工作,这样一来服务器只充当一个身份认证和消息中转的功能

**Comment by 0x00A0** [comment]
其实这样一来所有计算都在客户端了,反而对数据的篡改也只能体现在攻击者本地的客户端上,其他正常玩家仍然是完全遵从服务器的指令的

**Comment by WheatBox** [comment]
哦哦，你是说这个啊，目前来说采取的就是这种方案（不过写的比较烂，漏洞比较多），客户端负责运算，服务端负责判断消息是否能被允许执行然后进行转发，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WheatBox/WheatCloudSleep] 建议在通信中加入加密 (Issue #1)





 
其实这样一来所有计算都在客户端了,反而对数据的篡改也只能体现在攻击者本地的客户端上,其他正常玩家仍然是完全遵从服务器的指令的

**Comment by WheatBox** [comment]
加密方面我抽空研究一下，以前没有这方面的经验，可能得现学现卖

**Comment by WheatBox** [comment]
话说能请教一个问题么，就是服务器时候会运行着就突然卡住，也不知道为什么，后台也没有任何异常，就是突然卡住了，也没有断开连接的消息提示，这个困难已经困扰我一天了，也没有人能帮我，能请教一下一般这种情况是什么吗

**Comment by 0x00A0** [comment]
有日志吗,如果是linux服务器突然卡住的话可能是内存占用过高导致的OOM Kill,得检查代码里有没有内存泄漏的地方或者关闭系统的OOM检查; 如果是程序卡住的话那只能慢慢debug了(www

**Comment by WheatBox** [comment]
Windows，淦，我甚至还不知道是因为什么原因卡住的，悲伤

**Comment by 0x00A0** [comment]
emmm那你只能尽量多输出debug信息看看卡死前程序进行了哪些操作哦

**Comment by WheatBox** [comment]
OK，了解了
