### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by JiJiang233** [WheatBox/WheatCloudSleep#12]
1.这个游戏仅为44MB，也就是说有一些人会无限启动客户端来刷号占用服务器空间

2.可以无限放大，缩小

3.同名ID存在不会出错

**Comment by zhhhhhhhh** [comment]
1、是的，仅为44MB。关于无限启动客户端，已在服务端做了限制，达到一定数量后将无法继续新建连接
2、恭喜你发现了一个feature^_^
3、允许同名ID为游戏设计初期既确定的，如果后期不产生问题将会继续保持
                                                                                                                                                                        
--感谢您的建议与支持
