### ISSUE TITLE
server端linux编译问题

### ISSUE THREAD

**Issue by labman010** [WheatBox/WheatCloudSleep#16]
<img width="977" alt="WeChatbcb2cc8f7748fa061e4c2e397283a475" src="https://user-images.githubusercontent.com/21260632/190231427-fc7b4047-f5c8-4a5c-86ef-0e7856cb4016.png">

**Comment by ymx-mshk** [comment]
抱歉，之前提交的时候没在linux环境编译，新提交已修复此问题

**Comment by ymx-mshk** [comment]
抱歉，之前提交的时候没在linux环境编译，新提交已修复此问题

**Comment by labman010** [comment]
感谢对linux环境对支持
