### ISSUE TITLE
啥时候能整改完 是不是敏感词汇了

### ISSUE THREAD

**Issue by ZL0520** [WheatBox/WheatCloudSleep#22]
我和兄弟们都约好了 左下角 暗号鸡你太美.
这么快就喝茶了?

**Comment by WheatBox** [comment]
哎……的确是因为敏感词问题
抱歉，我也不知道啥时候能改完，因为现在警方要求我整改好后向他们汇报，他们审核之后确保没问题了才允许上线，如果还是有问题那就得继续整改，都到这个地步了，有可能要做的东西不只是敏感词屏蔽那么简单了，可能得做很多麻烦事情

**Comment by WheatBox** [comment]
说来我也挺委屈的，因为那条敏感言论是8月26日的，但是其实当时我就主动停服整改了，后来不放心，又主动停服整改了好多次，现在已经几乎没有这种现象了，即使出现了这种现象也会很快被公投出去然后自动封禁，不过这些现在看来也只是亡羊补牢罢了
吸取教训了，就当作是对我匆忙上线而没有把事情考虑周全，导致管理不当的惩罚罢

**Comment by 223333** [comment]
可以试试把消息通过baidu的文本审核检查一遍再发出，应该能过滤大部分敏感词汇

**Comment by 223333** [comment]
有免费的使用次数应该是够用的，平时看睡觉里面的人也不是很多

**Comment by WheatBox** [comment]
人还是比较多的，大多数时候都会好几十个人在里面，缩小一点看几乎是满屏都是人的那种

**Comment by WheatBox** [comment]
嗯，我去了解下看看baidu的文本审核

**Comment by qq1183512711** [comment]
类似alibaba,tencent都有文本审核的API,一般都能过滤得差不多,实在并发量太高收费的话,我觉得在加入页面加入广告给你提供收益其实是可以接受的

**Comment by WheatBox** [comment]
嗯，用这些API的话，一是网速问题，会有更高的延迟，二是价格也是个问题，再之后就是还很麻烦
我们这边还是先试着做一下敏感词屏蔽吧，再给网安看看，如果实在不行再去接入这些API

**Comment by LCcupid** [comment]
看看橘子审核的严不严格吧,不太严的话自己做一个也不麻烦.就是怕很严格,那样接入API是最好的了,自己做难免要长期维护,费用问题接点广告用来维护服务器和API没事的,开源项目变现都挺难的,广告是最好的方法了

**Comment by WheatBox** [comment]
> 想知道网安是怎么联系作者的，整改触发条件是什么，这种用户量少的小项目也会被喝茶啊。

网安是通过打电话的形式联系到我的，父母爷奶，还有什么老家的村委书记什么的我完全听都没听说过的人
去喝茶的触发条件是 B站上8月26日的一名玩家录制的实况视频里有那么一幕是有人发布了一条“野兽先辈”+国家领导人的名称+“说”的言论，这么一句，然后前几天被人发现了这一幕，然后举报了，然后查到软件开发者（我）的B站了，然后从我B站继续查下去的了，然后就查到我了，然后我就喝茶了，顺带一提我现在B站上发不了动态，公告板被强制清除了，那期视频下面我也发不了评论了

**Comment by WheatBox** [comment]
开服啦！（虽然服务器换到了香港，网络有点差）
