### ISSUE TITLE
什么时候继续开啊，等的花儿都谢了

### ISSUE THREAD

**Issue by super-zhang** [WheatBox/WheatCloudSleep#30]
什么时候继续开起来呀。等的花儿都谢了

**Comment by WheatBox** [comment]
绝大多数工作已经就绪，整改方面我感觉也都可以了
最近几天将服务器迁移到了香港（虽然延迟可能会有点小高）
决定下周末，或者下下周末发布新版本并重新开服（具体时间视现实情况而定）

**Comment by WheatBox** [comment]
开了
