### ISSUE TITLE
Memory safty problem in WheatTCPServer.cpp

### ISSUE THREAD

**Issue by B1aNB1aN** [WheatBox/WheatCloudSleep#4]
### location:

WheatTCPServer.cpp:81-82

### problem:

1. line 81:

不要用 = {0} 这样的方式初始化内存，在一些版本的msvc编译器中，这样的代码并不会完整初始化整个内存块，应当使用memset或者stl中的std::fill or std::fill_n类似的函数去初始化内存块。

3. line 82:

buf是一个null-terminated string，所以你在使用recv的时候应该留一个字节的null。要不然buf有可能超过WHEATTCP_BUFFERSIZE的大小，如果客户端发送等于WHEATTCP_BUFFERSIZE的数据。

**Comment by WheatBox** [comment]
修复了，感谢

**Comment by B1aNB1aN** [comment]
### location:

Function WheatTCPServer::SendMultiCommand

### problem:

1. 服务器没有限制客户端数量。
2. 在这个函数中，申请了一个固定大小的buf来发送MultiCommand。

结合上述两点，如果有大量客户端申请链接，并且触发问题函数，就会导致服务器进程的堆内存越界写。
